### ISSUE TITLE
Possibility to choose between a text or a tspan as main tag element

### ISSUE THREAD

**Issue by clementfrison** [techniq/react-svg-text#2]
Wonderful package very useful, thank you :)

I am using it with [react-vis](https://github.com/uber/react-vis) to have nice axis tick labels. In this particular use case you need to render a tspan and not a text element because there is already a text element.

So I think it could be cool nice to have an option to choose which tag element you want to render so more people could directly use your package.

Anyway it works great! Thanks for sharing your solution to this tricky problem

**Comment by techniq** [comment]
Thanks for the praise, glad you like it.  I see the benefit of being table to specify the root element, and took a quick look at react-vis's [axis docs](https://uber.github.io/react-vis/documentation/api-reference/axes), but was having difficult seeing how best to integrate the two.  It also seems like `<XAxis />` would need a `tickComponent` exposed on it's side, where you could my `<Text />` component too, something like

```jsx
<XAxis tickComponent={Text} />
```

or possible control the props yourself, since it appears they use `top`/`left` instead of `x`/`y`


```jsx
<XAxis tickComponent={({ left, top, ...props }) => <Text x={left} y={top} {...props} /> } />
```

Anyways, if I'm misunderstand something let me know.  I'm also open for pull requests if you see how best to integrate the two.

Lastly, I'm considering folding this project into [vx](https://github.com/hshoff/vx) as I've been doing a good bit of work over there.  It's a lower level library that other libraries like react-vis, [data-ui](https://github.com/williaster/data-ui), custom visuals, etc can use (basically a nice react layer over d3/svg).  My react-svg-text component will replace the current [@vx/text](https://github.com/hshoff/vx/tree/master/packages/vx-text) component, but you'll still be able to install/use it separately from anything else vx has (but you might find more you like)

**Comment by clementfrison** [comment]
Indeed they should have implemented tickComponent props so you can directly put a SVG text component. Instead they exposed a 'tickFormat' function that supports tspan svg react elements.
This is where I used you package after replacing the main text tag by a tspan tag.

But I think I will create an issue in react-vis too

I will take a look at vx, it seems nice for custom dataviz !
